from fastapi import FastAPI
from common.kafka import get_producer
from common.models import Packet
import time, threading

from prometheus_fastapi_instrumentator import Instrumentator
from prometheus_client import Counter

app = FastAPI(title="simulator-service")

Instrumentator().instrument(app).expose(app)

producer = get_producer()
PACKETS_SENT = Counter(
    "inspection_packets_generated_total",
    "Total packets generated by simulator"
)

def loop():
    while True:
        packet = Packet.new()
        producer.send("raw_packets", packet.dict())
        PACKETS_SENT.inc()
        print("[SIMULATOR] Packet sent:", packet.id)
        time.sleep(5)

@app.on_event("startup")
def start():
    threading.Thread(target=loop, daemon=True).start()

@app.get("/health")
def health():
    return {"status": "ok"}
